# Generated by Django 5.2 on 2025-04-26 15:01

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='别名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏标签',
                'verbose_name_plural': '游戏标签',
            },
        ),
        migrations.CreateModel(
            name='FrontUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='头像')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否是会员')),
                ('member_until', models.DateTimeField(blank=True, null=True, verbose_name='会员截止日期')),
                ('member_type', models.CharField(choices=[('free', '免费用户'), ('monthly', '月度会员'), ('quarterly', '季度会员'), ('yearly', '年度会员')], default='free', max_length=20, verbose_name='会员类型')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '前台用户',
                'verbose_name_plural': '前台用户',
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome图标类名，例如: fas fa-gamepad', max_length=50, verbose_name='图标类名')),
                ('color', models.CharField(blank=True, default='#6EBD6E', help_text='用于分类标签和图标背景', max_length=7, verbose_name='分类颜色')),
                ('order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.gamecategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='游戏标题')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='别名')),
                ('description', models.TextField(verbose_name='游戏描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/', verbose_name='缩略图')),
                ('iframe_url', models.URLField(max_length=500, verbose_name='游戏iframe地址')),
                ('iframe_width', models.CharField(default='100%', max_length=50, verbose_name='iframe宽度')),
                ('iframe_height', models.CharField(default='600', max_length=50, verbose_name='iframe高度')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('play_count', models.IntegerField(default=0, verbose_name='游玩次数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('status', models.CharField(choices=[('online', '已上线'), ('offline', '已下线'), ('pending', '待审核')], default='offline', max_length=20, verbose_name='状态')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(related_name='games', to='core.gamecategory', verbose_name='游戏分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='core.gametag', verbose_name='游戏标签')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('likes', models.JSONField(blank=True, default=list, verbose_name='点赞用户')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.game', verbose_name='游戏')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.gamecomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏评论',
                'verbose_name_plural': '游戏评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGameFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏收藏',
                'verbose_name_plural': '游戏收藏',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField(auto_now=True, verbose_name='最后游玩时间')),
                ('play_count', models.IntegerField(default=1, verbose_name='游玩次数')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏历史',
                'verbose_name_plural': '游戏历史',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
