# Generated by Django 5.2 on 2025-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamecomment_game_alter_gamecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, help_text='简短介绍，显示在游戏列表中', max_length=200, verbose_name='简单介绍'),
        ),
    ]
