# Generated by Django 5.2 on 2025-04-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergamefavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamefavorite',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamefavorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergamehistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamehistory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='FrontUser',
        ),
        migrations.DeleteModel(
            name='GameComment',
        ),
        migrations.DeleteModel(
            name='UserGameFavorite',
        ),
        migrations.DeleteModel(
            name='UserGameHistory',
        ),
    ]
