# Generated by Django 5.2 on 2025-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gamecomment_game_remove_gamecomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='标签名称'),
        ),
        migrations.AddIndex(
            model_name='gametag',
            index=models.Index(fields=['name'], name='core_gametag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='gametag',
            index=models.Index(fields=['is_active'], name='core_gametag_active_idx'),
        ),
    ]
