# Generated by Django 5.2 on 2025-05-12 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gametag_name_gametag_core_gametag_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网关名称')),
                ('gateway_type', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('braintree', 'Braintree'), ('adyen', 'Adyen')], max_length=20, verbose_name='网关类型')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('test_mode', models.BooleanField(default=True, verbose_name='测试模式')),
                ('config', models.JSONField(blank=True, default=dict, help_text='存储网关配置信息，内容根据网关类型不同', verbose_name='配置信息')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('success_url', models.CharField(default='/payment-success/', max_length=255, verbose_name='支付成功跳转URL')),
                ('cancel_url', models.CharField(default='/payment-cancel/', max_length=255, verbose_name='取消支付跳转URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付网关',
                'verbose_name_plural': '支付网关',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('period', models.CharField(choices=[('monthly', '月度'), ('yearly', '年度'), ('quarterly', '季度'), ('one_time', '一次性')], max_length=20, verbose_name='周期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('features', models.TextField(blank=True, help_text='每行一个功能点，将显示在前台', verbose_name='包含功能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订阅计划',
                'verbose_name_plural': '订阅计划',
                'ordering': ['price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始日期')),
                ('end_date', models.DateTimeField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('active', '活跃'), ('trial', '试用期'), ('expired', '已过期'), ('cancelled', '已取消'), ('pending', '待处理'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='支付网关返回的订阅ID', max_length=255, verbose_name='网关订阅ID')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='自动续费')),
                ('is_trial', models.BooleanField(default=False, verbose_name='是否试用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentgateway', verbose_name='支付网关')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan', verbose_name='订阅计划')),
            ],
            options={
                'verbose_name': '用户订阅',
                'verbose_name_plural': '用户订阅',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败'), ('refunded', '已退款'), ('partial_refund', '部分退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_type', models.CharField(choices=[('subscription', '会员订阅'), ('renewal', '续费'), ('upgrade', '升级'), ('downgrade', '降级'), ('refund', '退款')], max_length=20, verbose_name='交易类型')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='网关交易ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='网关响应')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentgateway', verbose_name='支付网关')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.subscription', verbose_name='关联订阅')),
            ],
            options={
                'verbose_name': '支付交易',
                'verbose_name_plural': '支付交易',
                'ordering': ['-created_at'],
            },
        ),
    ]
