# Generated by Django 5.2 on 2025-04-20 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接URL')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome图标类名，例如：fas fa-home', max_length=50, verbose_name='图标')),
                ('order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_panel.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单列表',
                'ordering': ['order', 'id'],
            },
        ),
    ]
