# Generated by Django 5.2 on 2025-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminuser_managers_alter_adminlog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='权限名称')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('category', models.CharField(choices=[('content', '内容管理'), ('game', '游戏管理'), ('user', '用户管理'), ('system', '系统设置')], default='content', max_length=20, verbose_name='权限分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.IntegerField(choices=[(10, 'Super Admin'), (20, 'Admin'), (30, 'Content Editor'), (40, 'Agent')], default=40, verbose_name='角色类型'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='admin_users_with_permission', to='admin_panel.permission', verbose_name='自定义权限'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='adminuser_set', related_query_name='adminuser', to='admin_panel.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='admin_panel.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='admin_panel.role', verbose_name='自定义角色'),
        ),
    ]
