# Generated by Django 5.2 on 2025-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_permission_alter_adminuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
    ]
