# Generated by Django 5.2 on 2025-04-23 10:39

import colorfield.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_adminuser_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('alias', models.CharField(blank=True, help_text='英文字母、数字和连字符，用于URL友好显示', max_length=100, verbose_name='分类别名')),
                ('color', colorfield.fields.ColorField(blank=True, default='#6EBD6E', help_text='用于分类标签和图标背景', image_field=None, max_length=25, samples=None, verbose_name='分类颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用此分类')),
                ('game_count', models.IntegerField(default=0, editable=False, verbose_name='游戏数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='admin_panel.gamecategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类列表',
                'ordering': ['order', 'id'],
            },
        ),
    ]
