# Generated by Django 5.2 on 2025-04-24 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_gamecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '游戏标签',
                'verbose_name_plural': '游戏标签',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='游戏名称')),
                ('description', models.TextField(blank=True, verbose_name='游戏描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/', verbose_name='缩略图')),
                ('iframe_url', models.URLField(max_length=500, verbose_name='游戏iframe链接')),
                ('iframe_width', models.CharField(default='100%', max_length=50, verbose_name='iframe宽度')),
                ('iframe_height', models.CharField(default='600', max_length=50, verbose_name='iframe高度')),
                ('status', models.CharField(choices=[('online', '已上线'), ('offline', '已下线'), ('pending', '待审核')], default='offline', max_length=20, verbose_name='状态')),
                ('player_count', models.IntegerField(default=0, verbose_name='游玩次数')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='admin_panel.gamecategory', verbose_name='游戏分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='admin_panel.gametag', verbose_name='游戏标签')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'ordering': ['-added_date'],
            },
        ),
    ]
