# Generated by Django 5.2 on 2025-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_gametag_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta描述'),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta关键词'),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta标题'),
        ),
    ]
