# Generated by Django 5.2 on 2025-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_game_meta_description_game_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('site_description', models.TextField(blank=True, verbose_name='网站描述')),
                ('site_keywords', models.CharField(blank=True, help_text='多个关键词请用英文逗号分隔', max_length=255, verbose_name='网站关键词')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='网站Logo')),
                ('site_favicon', models.ImageField(blank=True, help_text='推荐尺寸: 32x32 像素, 格式: .ico, .png', null=True, upload_to='site_settings/', verbose_name='网站图标')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_address', models.CharField(blank=True, max_length=255, verbose_name='联系地址')),
                ('wechat_qrcode', models.CharField(blank=True, max_length=100, verbose_name='微信公众号')),
                ('weibo_account', models.CharField(blank=True, max_length=100, verbose_name='微博账号')),
                ('enable_seo', models.BooleanField(default=True, verbose_name='启用SEO优化')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
