# Generated by Django 5.2 on 2025-04-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_seo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='wechat_qrcode',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='weibo_account',
        ),
    ]
