# Generated by Django 5.2 on 2025-04-25 04:43

from django.db import migrations
from django.utils import timezone

def add_seo_menu_item(apps, schema_editor):
    """
    添加SEO设置菜单项
    """
    Menu = apps.get_model('admin_panel', 'Menu')
    
    # 获取父级菜单（系统设置菜单）
    parent_menu = None
    try:
        # 尝试查找"系统设置"菜单作为父级
        parent_menu = Menu.objects.get(name='系统设置')
    except Menu.DoesNotExist:
        # 如果不存在，创建新的系统设置菜单
        parent_menu = Menu.objects.create(
            name='系统设置',
            url='#',  # 链接设为空，表示仅作为父级菜单
            icon='fas fa-cogs',
            parent=None,
            order=90,
            is_active=True,
            created_time=timezone.now()
        )
    
    # 检查SEO设置菜单是否已存在
    if not Menu.objects.filter(name='SEO设置').exists():
        Menu.objects.create(
            name='SEO设置',
            url='/admin-panel/seo-settings/',
            icon='fas fa-search',
            parent=parent_menu,
            order=20,  # 排序在网站设置后面
            is_active=True,
            created_time=timezone.now()
        )

def remove_seo_menu_item(apps, schema_editor):
    """
    移除SEO设置菜单项（回滚操作）
    """
    Menu = apps.get_model('admin_panel', 'Menu')
    
    try:
        seo_menu = Menu.objects.get(name='SEO设置')
        seo_menu.delete()
    except Menu.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.RunPython(add_seo_menu_item, remove_seo_menu_item),
    ]
