# Generated by Django 5.2 on 2025-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_add_seo_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_format', models.CharField(default='{页面名称} - {网站名称}', max_length=255, verbose_name='页面标题格式')),
                ('description_format', models.TextField(default='{页面名称}是{网站名称}的一部分，提供最好玩的HTML5游戏体验。', verbose_name='页面描述格式')),
                ('enable_sitemap', models.BooleanField(default=True, verbose_name='启用自动生成网站地图')),
                ('enable_canonical', models.BooleanField(default=True, verbose_name='启用规范链接标签')),
                ('url_trailing_slash', models.BooleanField(default=True, verbose_name='URL末尾添加斜杠')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SEO设置',
                'verbose_name_plural': 'SEO设置',
            },
        ),
    ]
