# Generated by Django 5.2 on 2025-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='category_url_pattern',
            field=models.CharField(default='categories/{slug}/', help_text='可用变量: {slug}, {id}', max_length=100, verbose_name='分类页URL结构'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='game_url_pattern',
            field=models.CharField(default='games/{slug}/', help_text='可用变量: {slug}, {id}, {category_slug}', max_length=100, verbose_name='游戏页URL结构'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='tag_url_pattern',
            field=models.CharField(default='tags/{slug}/', help_text='可用变量: {slug}, {id}', max_length=100, verbose_name='标签页URL结构'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='use_date_in_url',
            field=models.BooleanField(default=False, help_text='例如: /2025/04/game-name/', verbose_name='在URL中包含日期'),
        ),
    ]
