# Generated by Django 5.2 on 2025-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_seosettings_category_url_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-gamepad', help_text='Font Awesome图标类名，例如: fas fa-gamepad', max_length=50, verbose_name='分类图标'),
        ),
    ]
