# Generated by Django 5.2 on 2025-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_gamecategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameTag',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
