# Generated by Django 5.2 on 2025-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_gamecategory_parent_delete_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置列表',
                'ordering': ['key'],
            },
        ),
    ]
