# Generated by Django 5.2 on 2025-04-30 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_configsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at'], 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
        migrations.AlterModelOptions(
            name='configsettings',
            options={'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='configsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='configsettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='category_url_pattern',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='description_format',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='enable_canonical',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='enable_sitemap',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='game_url_pattern',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='tag_url_pattern',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='title_format',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='url_trailing_slash',
        ),
        migrations.RemoveField(
            model_name='seosettings',
            name='use_date_in_url',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间'),
        ),
        migrations.AddField(
            model_name='configsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='description_template',
            field=models.TextField(default='{页面名}是GameHub的一部分，提供最好玩的HTML5游戏体验。', verbose_name='描述模板'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='keywords',
            field=models.CharField(blank=True, default='HTML5游戏,小游戏,休闲游戏', max_length=500, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_description_template',
            field=models.TextField(blank=True, default='', verbose_name='OG描述模板'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG图片'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_title_template',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='OG标题模板'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='page_type',
            field=models.CharField(default='default', max_length=50, unique=True, verbose_name='页面类型'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='title_template',
            field=models.CharField(default='{页面名} - GameHub', max_length=200, verbose_name='标题模板'),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='配置描述'),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='value',
            field=models.TextField(verbose_name='配置值'),
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_panel_admin_user',
        ),
    ]
