# Generated by Django 5.2 on 2025-05-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_admin_session'),
        ('admin_panel', '0016_alter_adminlog_options_alter_configsettings_options_and_more'),
    ]

    operations = [
    ]
