# Generated by Django 5.2 on 2025-05-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminsession_user_id'),
        ('admin_panel', '0017_merge_20250507_0957'),
    ]

    operations = [
    ]
