# Generated by Django 5.2 on 2025-05-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_merge_20250507_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSession',
        ),
    ]
