# Generated by Django 5.2 on 2025-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_delete_adminsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='管理员ID')),
            ],
            options={
                'verbose_name': '后台会话',
                'verbose_name_plural': '后台会话',
                'db_table': 'admin_sessions',
            },
        ),
    ]
