# Generated by Django 5.2 on 2025-05-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_adminsession'),
    ]

    operations = [
        # 删除AdminSession模型
        migrations.DeleteModel(
            name='AdminSession',
        ),
    ]
