# Generated by Django 5.2 on 2025-05-07 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_remove_admin_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(10, 'Super Admin'), (20, 'Admin'), (30, 'Content Editor'), (40, 'Agent')], default=40, verbose_name='角色类型')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='状态')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='admin/avatars/', verbose_name='头像')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='admin_users_with_permission', to='admin_panel.permission', verbose_name='自定义权限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '管理员资料',
                'verbose_name_plural': '管理员资料列表',
                'ordering': ['-created_time'],
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
