# Generated by Django 5.2 on 2025-05-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_add_payment_menu_item'),
        ('admin_panel', '0022_add_admin_profile'),
    ]

    operations = [
    ]
