# Generated by Django 5.2 on 2025-05-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_payment_configs'),
    ]

    operations = [
        # 先创建PaymentGateway表
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网关名称')),
                ('gateway_type', models.CharField(choices=[('paypal', 'PayPal'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('stripe', 'Stripe'), ('custom', '自定义')], max_length=20, verbose_name='网关类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('test_mode', models.BooleanField(default=True, verbose_name='测试模式')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('success_url', models.CharField(max_length=255, verbose_name='支付成功跳转URL')),
                ('cancel_url', models.CharField(max_length=255, verbose_name='支付取消跳转URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付网关',
                'verbose_name_plural': '支付网关',
                'ordering': ['display_order', 'gateway_type'],
            },
        ),
        
        # 添加is_default字段到PayPalConfig
        migrations.AddField(
            model_name='paypalconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
        
        # 临时添加一个PaymentGateway，供现有PayPalConfig使用
        migrations.RunSQL(
            "INSERT INTO admin_panel_paymentgateway (name, gateway_type, is_active, is_default, test_mode, display_order, success_url, cancel_url, created_at, updated_at) VALUES ('默认PayPal网关', 'paypal', 1, 1, 1, 0, '/payment-success/', '/payment-cancel/', datetime('now'), datetime('now'))",
            "DELETE FROM admin_panel_paymentgateway WHERE name='默认PayPal网关'",
        ),
        
        # 添加gateway字段到PayPalConfig
        migrations.AddField(
            model_name='paypalconfig',
            name='gateway',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paypal_config', to='admin_panel.paymentgateway', verbose_name='所属网关'),
            preserve_default=False,
        ),
        
        # 移除不需要的字段
        migrations.RemoveField(
            model_name='paypalconfig',
            name='test_mode',
        ),
        migrations.RemoveField(
            model_name='paypalconfig',
            name='return_url',
        ),
        migrations.RemoveField(
            model_name='paypalconfig',
            name='cancel_url',
        ),
    ] 