# Generated by Django 5.2 on 2025-05-12 07:15

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0025_add_payment_gateway_tables'),
    ]

    operations = [
        # 创建支付宝配置模型
        migrations.CreateModel(
            name='AlipayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app_id', models.CharField(max_length=128, verbose_name='应用ID')),
                ('private_key', models.TextField(verbose_name='应用私钥')),
                ('alipay_public_key', models.TextField(verbose_name='支付宝公钥')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alipay_config', to='admin_panel.paymentgateway', verbose_name='所属网关')),
            ],
            options={
                'verbose_name': '支付宝配置',
                'verbose_name_plural': '支付宝配置',
                'abstract': False,
            },
        ),
        
        # 创建微信支付配置模型
        migrations.CreateModel(
            name='WeChatPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app_id', models.CharField(max_length=128, verbose_name='应用ID')),
                ('mch_id', models.CharField(max_length=32, verbose_name='商户号')),
                ('api_key', models.CharField(max_length=128, verbose_name='API密钥')),
                ('cert_file', models.FileField(blank=True, null=True, upload_to='certs/wechat/', verbose_name='证书文件')),
                ('key_file', models.FileField(blank=True, null=True, upload_to='certs/wechat/', verbose_name='密钥文件')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechatpay_config', to='admin_panel.paymentgateway', verbose_name='所属网关')),
            ],
            options={
                'verbose_name': '微信支付配置',
                'verbose_name_plural': '微信支付配置',
                'abstract': False,
            },
        ),
        
        # 创建交易记录模型
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易ID')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='订单ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('member_type', models.CharField(blank=True, max_length=10, verbose_name='会员类型')),
                ('billing_cycle', models.CharField(blank=True, max_length=20, verbose_name='计费周期')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='有效天数')),
                ('gateway_response', models.TextField(blank=True, verbose_name='网关响应')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='admin_panel.paymentgateway', verbose_name='支付网关')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付交易',
                'verbose_name_plural': '支付交易',
                'ordering': ['-created_at'],
            },
        ),
    ] 