# Generated by Django 5.2 on 2025-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_add_alipay_wechat_config_models'),
    ]

    operations = [
        # 添加client_id和client_secret字段到PayPalConfig
        migrations.AddField(
            model_name='paypalconfig',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户端ID'),
        ),
        migrations.AddField(
            model_name='paypalconfig',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户端密钥'),
        ),
    ] 