# Generated by Django 5.2 on 2025-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_paypal_config_add_client_fields'),
    ]

    operations = [
        # 添加is_default字段到MembershipPrice
        migrations.AddField(
            model_name='membershipprice',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
    ] 