# Generated by Django 5.2 on 2025-05-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_add_is_default_to_membership_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatpayconfig',
            name='gateway',
        ),
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-timestamp'], 'verbose_name': '管理员日志', 'verbose_name_plural': '管理员日志'},
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('braintree', 'Braintree'), ('adyen', 'Adyen'), ('custom', '自定义')], max_length=20, verbose_name='网关类型'),
        ),
        migrations.CreateModel(
            name='AdyenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merchant_account', models.CharField(max_length=255, verbose_name='商户账号')),
                ('api_key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('client_key', models.CharField(max_length=255, verbose_name='客户端密钥')),
                ('hmac_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='HMAC密钥')),
                ('live_endpoint_prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='生产环境端点前缀')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adyen_config', to='admin_panel.paymentgateway', verbose_name='所属网关')),
            ],
            options={
                'verbose_name': 'Adyen配置',
                'verbose_name_plural': 'Adyen配置',
            },
        ),
        migrations.CreateModel(
            name='BraintreeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merchant_id', models.CharField(max_length=255, verbose_name='商户ID')),
                ('public_key', models.CharField(max_length=255, verbose_name='公钥')),
                ('private_key', models.CharField(max_length=255, verbose_name='私钥')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='braintree_config', to='admin_panel.paymentgateway', verbose_name='所属网关')),
            ],
            options={
                'verbose_name': 'Braintree配置',
                'verbose_name_plural': 'Braintree配置',
            },
        ),
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publishable_key', models.CharField(max_length=255, verbose_name='可发布密钥')),
                ('secret_key', models.CharField(max_length=255, verbose_name='密钥')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook密钥')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_config', to='admin_panel.paymentgateway', verbose_name='所属网关')),
            ],
            options={
                'verbose_name': 'Stripe配置',
                'verbose_name_plural': 'Stripe配置',
            },
        ),
        migrations.DeleteModel(
            name='AlipayConfig',
        ),
        migrations.DeleteModel(
            name='WeChatPayConfig',
        ),
    ]
