# Generated by Django 5.2 on 2025-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_remove_wechatpayconfig_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalconfig',
            name='cancel_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='支付取消跳转URL'),
        ),
        migrations.AddField(
            model_name='paypalconfig',
            name='return_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='支付成功跳转URL'),
        ),
        migrations.AddField(
            model_name='paypalconfig',
            name='test_mode',
            field=models.BooleanField(default=True, verbose_name='测试模式'),
        ),
    ]
