# Generated by Django 5.2 on 2025-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_paypalconfig_cancel_url_paypalconfig_return_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalconfig',
            name='cancel_url',
            field=models.CharField(default='/payment/cancel/', max_length=255, verbose_name='支付取消URL'),
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='return_url',
            field=models.CharField(default='/payment/success/', max_length=255, verbose_name='支付成功URL'),
        ),
    ]
