# Generated by Django 5.2 on 2025-05-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_alter_paypalconfig_cancel_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adyenconfig',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='braintreeconfig',
            name='gateway',
        ),
        migrations.DeleteModel(
            name='MembershipPrice',
        ),
        migrations.RemoveField(
            model_name='stripeconfig',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='paypalconfig',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdyenConfig',
        ),
        migrations.DeleteModel(
            name='BraintreeConfig',
        ),
        migrations.DeleteModel(
            name='StripeConfig',
        ),
        migrations.DeleteModel(
            name='PayPalConfig',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
