# Generated by Django 5.2 on 2025-06-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='广告名称')),
                ('position', models.CharField(choices=[('header', '页面顶部'), ('sidebar', '侧边栏'), ('game_between', '游戏间隙'), ('footer', '页面底部')], max_length=20, verbose_name='广告位置')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='广告图片')),
                ('url', models.URLField(verbose_name='广告链接')),
                ('html_code', models.TextField(blank=True, help_text='如果使用第三方广告代码，请填写此字段', verbose_name='HTML代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='点击次数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='展示次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='分类图片')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome 6+ icon class, e.g., "fa-solid fa-gamepad"', max_length=100, verbose_name='Icon Class')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='games.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='游戏标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(verbose_name='游戏描述')),
                ('iframe_url', models.URLField(verbose_name='游戏iframe地址')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='游戏缩略图')),
                ('content', models.TextField(blank=True, verbose_name='游戏内容')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(related_name='games', to='games.category', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
