# Generated by Django 5.2 on 2025-04-25 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='games.gamecategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='游戏标题')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='别名')),
                ('description', models.TextField(verbose_name='游戏描述')),
                ('thumbnail', models.ImageField(upload_to='games/thumbnails/', verbose_name='缩略图')),
                ('iframe_url', models.URLField(verbose_name='游戏iframe地址')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='评分')),
                ('play_count', models.IntegerField(default=0, verbose_name='游玩次数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(related_name='games', to='games.gamecategory', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏评论',
                'verbose_name_plural': '游戏评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGameFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='games.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏收藏',
                'verbose_name_plural': '游戏收藏',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField(auto_now=True, verbose_name='最后游玩时间')),
                ('play_count', models.IntegerField(default=1, verbose_name='游玩次数')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='games.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏历史',
                'verbose_name_plural': '游戏历史',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
