# Generated by Django 5.2 on 2025-05-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='auto_detect_language',
            field=models.BooleanField(default=False, help_text="Automatically detect and use the user's browser language if available", verbose_name='Auto-detect User Language'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='enable_language_switcher',
            field=models.BooleanField(default=True, help_text='Show language switcher in the site header', verbose_name='Enable Language Switcher'),
        ),
    ]
