# Generated by Django 5.2 on 2025-05-19 03:15

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_websitesetting_auto_detect_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='账单地址'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='billing_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='billing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='账单国家'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='failure_reason',
            field=models.TextField(blank=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='fraud_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='欺诈检测详情'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='payment_method_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='支付方式代码'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='payment_processor_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='支付处理器响应'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='security_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='安全哈希'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='税号'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='用户代理'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='账单城市'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='fraud_status',
            field=models.CharField(choices=[('unknown', '未知'), ('accepted', '通过'), ('rejected', '拒绝'), ('review', '人工审核')], default='unknown', max_length=10, verbose_name='欺诈状态'),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_code', models.CharField(max_length=50, verbose_name='支付方式代码')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('provider_reference', models.CharField(blank=True, max_length=255, verbose_name='提供商参考号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.membershippayment', verbose_name='支付记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付尝试',
                'verbose_name_plural': '支付尝试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('invoice_date', models.DateTimeField(verbose_name='发票日期')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF文件')),
                ('sent_to_email', models.BooleanField(default=False, verbose_name='已发送邮件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='games.membershippayment', verbose_name='支付记录')),
            ],
            options={
                'verbose_name': '支付发票',
                'verbose_name_plural': '支付发票',
                'ordering': ['-created_at'],
            },
        ),
    ]
