# Generated by Django 5.2 on 2025-04-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_frontuser_alter_gamecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='likes',
            field=models.JSONField(blank=True, default=list, verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='games.gamecomment', verbose_name='父评论'),
        ),
    ]
