# Generated by Django 5.2 on 2025-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_size',
            field=models.CharField(choices=[('728x90', '728 x 90 (Leaderboard)'), ('300x250', '300 x 250 (Medium Rectangle)'), ('320x50', '320 x 50 (Mobile Banner)'), ('300x600', '300 x 600 (Half Page)'), ('970x250', '970 x 250 (Billboard)'), ('320x480', '320 x 480 (Mobile Interstitial)'), ('responsive', 'Responsive'), ('custom', 'Custom Size')], default='responsive', max_length=20, verbose_name='Ad Size'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('display', 'Display Ad'), ('text', 'Text Ad'), ('native', 'Native Ad'), ('interstitial', 'Interstitial Ad'), ('video', 'Video Ad')], default='display', max_length=20, verbose_name='Ad Type'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adsense_publisher_id',
            field=models.CharField(blank=True, help_text='Google AdSense publisher ID', max_length=100, verbose_name='AdSense Publisher ID'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adsense_slot_id',
            field=models.CharField(blank=True, help_text='Google AdSense slot ID', max_length=100, verbose_name='AdSense Slot ID'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='adsense_unit_id',
            field=models.CharField(blank=True, help_text='Google AdSense ad unit ID', max_length=100, verbose_name='AdSense Unit ID'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Click through rate percentage', max_digits=5, verbose_name='Click Through Rate'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated', max_digits=10, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='url',
            field=models.URLField(blank=True, verbose_name='Advertisement URL'),
        ),
    ]
