# Generated by Django 5.2 on 2025-04-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamecomment_likes_gamecomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接URL')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icon图标类名，例如：bi bi-house', max_length=50, verbose_name='图标')),
                ('order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_external', models.BooleanField(default=False, help_text='勾选表示链接会在新窗口打开', verbose_name='是否外部链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='games.frontmenu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '前台菜单',
                'verbose_name_plural': '前台菜单',
                'ordering': ['order', 'id'],
            },
        ),
    ]
