# Generated by Django 5.2 on 2025-05-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_membershippayment_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider_class',
            field=models.CharField(choices=[('payments.dummy.DummyProvider', 'Dummy Provider (Testing)'), ('payments.paypal.PaypalProvider', 'PayPal'), ('payments.stripe.StripeProvider', 'Stripe'), ('payments.manual.ManualProvider', 'Manual Payment'), ('payments.banktransfer.BankTransferProvider', 'Bank Transfer')], max_length=255, verbose_name='提供商类'),
        ),
    ]
