# Generated by Django 5.2 on 2025-06-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_advertisement_ad_size_advertisement_ad_type_and_more'),
    ]

    operations = [
    ]
