# Generated by Django 5.2 on 2025-04-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_frontmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamehistory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamefavorite',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergamefavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamefavorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergamehistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
        migrations.DeleteModel(
            name='GameComment',
        ),
        migrations.DeleteModel(
            name='UserGameFavorite',
        ),
        migrations.DeleteModel(
            name='UserGameHistory',
        ),
    ]
