# Generated by Django 5.2 on 2025-04-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_gamecomment_game_remove_usergamehistory_game_and_more'),
    ]

    operations = [
        # 重新指定依赖关系，替换内部模型为core中的模型
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # 使用state_operations确保正确处理模型状态
                # 这里不需要数据库操作，因为表已经在core应用中创建
            ],
        ),
    ]
