# Generated by Django 5.2 on 2025-04-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_summary'),
        ('games', '0006_auto_20250427_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontGameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('likes', models.JSONField(blank=True, default=list, verbose_name='点赞用户')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_comments', to='core.game', verbose_name='游戏')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='games.frontgamecomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to='games.frontuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '前台游戏评论',
                'verbose_name_plural': '前台游戏评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrontGameFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_favorited_by', to='core.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_favorites', to='games.frontuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '前台游戏收藏',
                'verbose_name_plural': '前台游戏收藏',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='FrontGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField(auto_now=True, verbose_name='最后游玩时间')),
                ('play_count', models.IntegerField(default=1, verbose_name='游玩次数')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_history', to='core.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to='games.frontuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '前台游戏历史',
                'verbose_name_plural': '前台游戏历史',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
