# Generated by Django 5.2 on 2025-04-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_frontgamecomment_frontgamefavorite_frontgamehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='特权名称')),
                ('description', models.TextField(verbose_name='特权描述')),
                ('membership_level', models.PositiveSmallIntegerField(choices=[(1, '基础会员'), (2, '高级会员'), (3, '终极会员')], verbose_name='会员等级要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '会员特权',
                'verbose_name_plural': '会员特权',
                'ordering': ['membership_level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='交易日期')),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('unionpay', '银联支付')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='交易状态')),
                ('transaction_type', models.CharField(choices=[('subscription', '会员订阅'), ('upgrade', '会员升级'), ('renewal', '会员续费'), ('purchase', '游戏购买')], max_length=20, verbose_name='交易类型')),
                ('description', models.CharField(max_length=200, verbose_name='交易描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='games.frontuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-date'],
            },
        ),
    ]
