# Generated by Django 5.2 on 2025-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_summary'),
        ('games', '0008_membershipfeature_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='billing_cycle',
            field=models.CharField(default='monthly', max_length=20, verbose_name='计费周期'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='data_collection',
            field=models.BooleanField(default=True, verbose_name='数据收集'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='电子邮件通知'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='game_history_visibility',
            field=models.BooleanField(default=True, verbose_name='游戏历史可见性'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='game_updates',
            field=models.BooleanField(default=True, verbose_name='游戏更新通知'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='marketing_emails',
            field=models.BooleanField(default=False, verbose_name='营销邮件'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='membership_renewal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员续费日期'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员开始日期'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='membership_status',
            field=models.CharField(default='inactive', max_length=20, verbose_name='会员状态'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='profile_visibility',
            field=models.BooleanField(default=True, verbose_name='个人资料可见性'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='core.game', verbose_name='已购买游戏'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='subscription_alerts',
            field=models.BooleanField(default=True, verbose_name='订阅提醒'),
        ),
    ]
