# Generated by Django 5.2 on 2025-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_frontuser_billing_cycle_frontuser_data_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
    ]
