# Generated by Django 5.2 on 2025-04-30 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_remove_gamecomment_game_remove_gamecomment_parent_and_more'),
        ('games', '0010_frontuser_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='交易时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game', verbose_name='相关游戏'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='membership_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='会员时长(天)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('free', '免费用户'), ('monthly', '月度会员'), ('quarterly', '季度会员'), ('yearly', '年度会员')], max_length=20, null=True, verbose_name='会员类型'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_details',
            field=models.JSONField(blank=True, null=True, verbose_name='支付详情'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='外部交易号'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='frontuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='front_user_set', related_query_name='front_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='frontuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='front_user_set', related_query_name='front_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('membership', '会员购买'), ('game', '游戏购买'), ('points', '积分购买'), ('gift', '礼物赠送'), ('refund', '退款')], max_length=20, verbose_name='交易类型'),
        ),
        migrations.AlterModelTable(
            name='frontuser',
            table='games_front_user',
        ),
    ]
