# Generated by Django 5.2 on 2025-05-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gamecomment_game_remove_gamecomment_parent_and_more'),
        ('games', '0011_alter_transaction_options_remove_transaction_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipfeature',
            options={'ordering': ['membership_level', 'priority', 'id'], 'verbose_name': '会员特权', 'verbose_name_plural': '会员特权'},
        ),
        migrations.AddField(
            model_name='frontgamecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='frontgamehistory',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='是否通关'),
        ),
        migrations.AddField(
            model_name='frontgamehistory',
            name='play_time',
            field=models.PositiveIntegerField(default=0, verbose_name='总游玩时间(分钟)'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号锁定截止时间'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='高级用户可以访问特殊功能', verbose_name='高级用户'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录尝试时间'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次密码修改时间'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='login_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='登录尝试次数'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='用户偏好设置'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='core.gamecategory', verbose_name='偏好游戏分类'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='preferred_tags',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='core.gametag', verbose_name='偏好游戏标签'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('moderator', '版主'), ('contributor', '贡献者'), ('vip', 'VIP用户')], default='user', max_length=20, verbose_name='用户角色'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='会话密钥'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='社交账号链接'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用两步验证'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='两步验证密钥'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='验证令牌'),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证令牌创建时间'),
        ),
        migrations.AddField(
            model_name='membershipfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap Icon图标类名，例如：bi bi-star', max_length=50, verbose_name='特权图标'),
        ),
        migrations.AddField(
            model_name='membershipfeature',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='数字越小优先级越高', verbose_name='显示优先级'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作管理员'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='交易备注'),
        ),
    ]
