# Generated by Django 5.2 on 2025-05-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_frontend_session'),
        ('games', '0012_alter_membershipfeature_options_and_more'),
    ]

    operations = [
    ]
