# Generated by Django 5.2 on 2025-05-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_frontendsession_user_id'),
        ('games', '0013_merge_20250507_0957'),
    ]

    operations = [
    ]
