# Generated by Django 5.2 on 2025-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_delete_frontendsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '前台会话',
                'verbose_name_plural': '前台会话',
                'db_table': 'frontend_sessions',
                'indexes': [models.Index(fields=['expire_date'], name='front_session_expire_idx'), models.Index(fields=['session_key'], name='front_session_key_idx')],
            },
        ),
    ]
