# Generated by Django 5.2 on 2025-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_frontendsession'),
    ]

    operations = [
        # 删除FrontendSession模型
        migrations.DeleteModel(
            name='FrontendSession',
        ),
    ]
