# Generated by Django 5.2 on 2025-05-07 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gamecomment_game_remove_gamecomment_parent_and_more'),
        ('games', '0017_remove_frontend_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否是会员')),
                ('member_until', models.DateTimeField(blank=True, null=True, verbose_name='会员截止日期')),
                ('member_type', models.CharField(choices=[('free', '免费用户'), ('monthly', '月度会员'), ('quarterly', '季度会员'), ('yearly', '年度会员')], default='free', max_length=20, verbose_name='会员类型')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='电子邮件通知')),
                ('game_updates', models.BooleanField(default=True, verbose_name='游戏更新通知')),
                ('subscription_alerts', models.BooleanField(default=True, verbose_name='订阅提醒')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='营销邮件')),
                ('profile_visibility', models.BooleanField(default=True, verbose_name='个人资料可见性')),
                ('game_history_visibility', models.BooleanField(default=True, verbose_name='游戏历史可见性')),
                ('data_collection', models.BooleanField(default=True, verbose_name='数据收集')),
                ('membership_status', models.CharField(default='inactive', max_length=20, verbose_name='会员状态')),
                ('membership_start_date', models.DateTimeField(blank=True, null=True, verbose_name='会员开始日期')),
                ('membership_renewal_date', models.DateTimeField(blank=True, null=True, verbose_name='会员续费日期')),
                ('billing_cycle', models.CharField(default='monthly', max_length=20, verbose_name='计费周期')),
                ('is_premium', models.BooleanField(default=False, help_text='高级用户可以访问特殊功能', verbose_name='高级用户')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('moderator', '版主'), ('contributor', '贡献者'), ('vip', 'VIP用户')], default='user', max_length=20, verbose_name='用户角色')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='社交账号链接')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='用户偏好设置')),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='profile_preferred_by_users', to='core.gamecategory', verbose_name='偏好游戏分类')),
                ('preferred_tags', models.ManyToManyField(blank=True, related_name='profile_preferred_by_users', to='core.gametag', verbose_name='偏好游戏标签')),
                ('purchased_games', models.ManyToManyField(blank=True, related_name='profile_purchasers', to='core.game', verbose_name='已购买游戏')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'games_user_profile',
            },
        ),
    ]
