# Generated by Django 5.2 on 2025-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_update_user_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
    ]
