# Generated by Django 5.2 on 2025-05-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_userprofile_avatar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
